import './globals.css'
import { Inter } from 'next/font/google'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='bg-orange-400 text-black prose prose-xl prose-slate dark:prose-invert mx-auto min-h-screen'>
          <Header />
          <div className='flex overflow-hidden'>
            <div className='max-w-screen-2lg mx-auto mt-28'>
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  )
}
